config/routes.rb
MailRegideaCom::Application.routes.draw do
  get "upload/show"
  get "upload/get"

  resources :portfolios , :except => [:update, :destroy, :new, :edit]

  get "pages/home"
  get "pages/contact"
  get "pages/clients"
  get "pages/portf"
  get "pages/about"

 match '/portf', 	:to  => 'pages#portf'

 match '/contact',	:to  => 'pages#contact'
 match '/about',         :to => 'pages#about'
 match '/clients',      :to  => 'pages#clients'
 match '/',             :to  => 'pages#home'

resources :pages

 root :to => 'pages#home'

end

app/models/picture.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
class Picture < ActiveRecord::Base

  validates_format_of :content_type, 
                      with: /^image/,
                      message: "--- you can only upload pictures"

  def uploaded_picture=(picture_field)
    self.name         = base_part_of(picture_field.original_filename)
    self.content_type = picture_field.content_type.chomp
    self.data         = picture_field.read
  end

  def base_part_of(file_name)
    File.basename(file_name).gsub(/[^\w._-]/, '')
  end
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  attr_accessible :image_url, :image_url_pr, :title, :title_o
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
#!/bin/env ruby
## encoding: utf-8
#
class PagesController < ApplicationController
  def home
  	@title = 'Главная страница'
  end

  def contact
  	@title = 'Контакты'
  end

  def clients
  	@title = 'Клиенты'
  end

  def portf
  	@title = ' Портфулио'
  end
  def about
  	@title = 'О компании'
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  # GET /portfolios
  # GET /portfolios.json
  def index
 #   @portfolios = Portfolio.all
     @portfolios = Portfolio.paginate page: params[:page] , per_page: 4 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @portfolios }
    end
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @portfolio }
    end
  end

  # GET /portfolios/new
  # GET /portfolios/new.json
  def new
    @portfolio = Portfolio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @portfolio }
    end
  end

  # GET /portfolios/1/edit
  def edit
    @portfolio = Portfolio.find(params[:id])
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(params[:portfolio])

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render json: @portfolio, status: :created, location: @portfolio }
      else
        format.html { render action: "new" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /portfolios/1
  # PUT /portfolios/1.json
  def update
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio.update_attributes(params[:portfolio])
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/upload_controller.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
class UploadController < ApplicationController
  def get
    @picture = Picture.new
  end
  # . . .

  def save
    @picture = Picture.new(params[:picture])
    if @picture.save
      redirect_to(action: 'show', id: @picture.id)
    else
      render(action: :get)
    end
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def picture
    @picture = Picture.find(params[:id])
    send_data(@picture.data,
              filename: @picture.name,
              type: @picture.content_type,
              disposition: "inline")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/layouts/.application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MailRegideaCom</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/_footer.html.erb
  <div id="templatemo_footer">

         <a href="index.html" class="current">Home</a> | <a href="about.html">About Us</a> | <a href="services.html">Services</a> | <a href="blog.html">Blog</a> | <a href="contact.html">Contact Us</a> <br /><br />
        Copyright © 2048 <a href="#">Your Company Name</a> | Designed by <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a>

    </div> <!-- end of footer -->

app/views/layouts/_header.html.erb
     <div id="templatemo_header">
        <div id="site_title"> 
 <!--  		<%= image_tag("logo.png", :alt => "LOGO", :class => "round") %> <span>Копирайтинг для агробизнеса</span>   -->
<p>  Зеленая Долина  </p>
<div id="site_title_tel"> +7(499) 123-12-12  <br> info@site.ru </div>
	</div>
        <!-- end of site_title -->
    </div><!-- end of header -->

<div id="templatemo_menu">
        <ul>
		<li><%= link_to "Главная", root_path %></li> 
		<li><%= link_to "О Компании",about_path %></li>
		<li><%= link_to " Клиенты", clients_path %></li>

		<li><%= link_to "Портфoлио", portfolios_path %></li>

	<li><%= link_to "Контакты", contact_path %></li>

        </ul>
</div> <!-- end of menu -->



app/views/layouts/_pakets.html.erb
  <div id="templatemo_middle">
        <div id="container-4">
            <div id="service-1">
                <h1>Lorem Ipsum Dolor Sit Amet Adipiscing</h1>
                <p>Nullam non justo nisl, in luctus eros. Curabitur rutrum <a href="#">vulputate bibendum</a>. Curabitur ut nisl et sapien imperdiet mollis.</p>
            </div>
            <div id="service-2">
                <h1>Curabitur Neque Molestie Vitae Lobortis</h1>
                <p>Phasellus sodales iaculis elementum. Etiam est lectus, condimentum non adipiscing sed, <a href="#">dictum id arcu</a>. Pellentesque ultricies sollicitudin metus.</p>
            </div>
            <div id="service-3">
                <h1>Maecenas Nunc Gravida Sapien Auctor Lacinia</h1>
                <p>Morbi posuere, tortor eget accumsan volutpat, nibh ante auctor massa, <a href="#">a dapibus eros magna eu neque</a>. Cras venenatis aliquet tortor, vel congue tellus cursus eu. Sed cursus scelerisque sagittis.</p>
            </div>
             <div id="service-4">
                <h1>Nam Mauris N`ec Risus Bibendum Commodo</h1>
                <p>Vestibulum vel dui vitae metus mattis blandit a sit amet justo. <a href="#">Etiam consectetur</a> porta mi, a fermentum tortor laoreet sed.</p>
            </div>
            <ul>
                <li><a href="#service-1">Копирайтинг<span></span></a></li>
                <li><a href="#service-2">Public Relations<span></span></a></li>
                <li><a href="#service-3">Медиа<span>Cras sit amet sagittis nulla</span></a></li>
                <li><a href="#service-4">Полиграфия<span>Suspendisse consectetur</span></a></li>
            </ul>
        </div>
    </div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine:bold,bolditalic|Inconsolata:italic|Droid+Sans">

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Green Field Theme - Free CSS Template</title>
 <%= csrf_meta_tags %>
 <%= render 'layouts/stylesheets' %>

 <script type="text/javascript">

		$(function() {

               $('#container-4').tabs({ fxFade: true, fxSpeed: 'slow' });
																													        });

</script>
 <script type="text/javascript">

	$(function() {
	 $("#accordion").accordion({ header: "h3" });
	 $('#gallery a').lightBox({fixedNavigation:true});
	});


 </script>

<style type="text/css" media="screen, projection">
	#templatemo_middle {
		overflow: hidden;
		width: 960px;
		height: 320px;
		background: url(/assets/templatemo_middle.jpg) no-repeat
	}
</style>

</head>
<body>

<div id="templatemo_body_wrapper">
   <div id="templatemo_wrapper">

    <%= render 'layouts/header' %> 
 

    <%= render 'layouts/pakets' %>

    <div id="templatemo_main_base">
    <div id="templatemo_main">
    	
        <div class="content_box">
	 <%= yield %>

        </div>
    
    </div>    
    </div>	<!-- end of main_base -->
    <div id="templatemo_main_bottom"></div>
<%= render 'layouts/footer' %>    
	
    <div class="cleaner">  </div>
</div> <!-- end of wrapper -->
</div> <!-- end of body_wrapper -->

</body>
</html>

app/views/pages/.home.html.erb
<h2>  <%= @title %>  </h2>

<div id="menu_l"> <h3> Пакетное предложение </h3>

	<ul>
	<li> Для сельхозпроизводителей  </li>
	<li> Для сельхозпроизводителей  </li>
	<li> Для сельхозпроизводителей  </li>
	
	</ul>
<div>

app/views/pages/.portf.html.erb
<div class="demo">

<div id="accordion">
	<h3><a href="#">Тексты ддя сайтов </a></h3>
	<div>
		<p>
		Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer
		ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit
		amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut
		odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.
		</p>

	</div>
	<h3><a href="#">Текст для продвижения сайтов</a></h3>
	<div>
		<p>
		Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet
		purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor
		velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In
		suscipit faucibus urna.
		</p>
	</div>
	<h3><a href="#">Статьи для СМИ</a></h3>
	<div>
		<p>
		Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis.
		Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero
		ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis
		lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.
		</p>
		<ul>
			<li>List item one</li>
			<li>List item two</li>
			<li>List item three</li>
		</ul>
	</div>
	<h3><a href="#">Другое</a></h3>
	<div>
		<p>
		Cras dictum. Pellentesque habitant morbi tristique senectus et netus
		et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
		faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
		mauris vel est.
		</p>
<h2 id="example1">Example</h2>
<div id="gallery">
    <ul>
        <li>
            <a href="/assets/photos/image1.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery').lightBox();">
	     <%= image_tag("photos/thumb_image1.jpg" ) %>
            </a>
        </li>
        <li>
            <a href="/assets/photos/image2.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
	     <%= image_tag("photos/thumb_image2.jpg" ) %>
            </a>
        </li>
        <li>
            <a href="/assets/photos/image3.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
	     <%= image_tag("photos/thumb_image3.jpg" ) %>
            </a>
        </li>
        <li>
            <a href="photos/image4.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
	     <%= image_tag("photos/thumb_image4.jpg" ) %>
            </a>
        </li>
        <li>
            <a href="photos/image5.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
                  <%= image_tag("photos/thumb_image5.jpg" ) %> 
              
            </a>
        </li>
    </ul>
</div>




        <h3><a href="#">Другое</a></h3>
        <div>
                <p>
                Cras dictum. Pellentesque habitant morbi tristique senectus et netus
                et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
                faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
                mauris vel est.
                </p>
^M
<h2 id="example1">Example</h2>^M
<div id="gallery">^M
    <ul>^M
        <li>^M
            <a href="/assets/photos/image1.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery').lightBox();">^M
             <%= image_tag("photos/thumb_image1.jpg" ) %>
            </a>^M
        </li>^M
        <li>^M
            <a href="/assets/photos/image2.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
             <%= image_tag("photos/thumb_image2.jpg" ) %>
            </a>
        </li>^M
        <li>^M
            <a href="/assets/photos/image3.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">^M
             <%= image_tag("photos/thumb_image3.jpg" ) %>
            </a>
        </li>^M
        <li>^M
            <a href="photos/image4.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
             <%= image_tag("photos/thumb_image4.jpg" ) %>
            </a>
        </li>^M
        <li>^M
            <a href="photos/image5.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">^M
                  <%= image_tag("photos/thumb_image5.jpg" ) %> ^M
              ^M
            </a>^M
        </li>^M
    </ul>^M
</div>^M
        <h3><a href="#">Другое</a></h3>
        <div>
                <p>
                Cras dictum. Pellentesque habitant morbi tristique senectus et netus
                et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
                faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
                mauris vel est.
                </p>
^M
<h2 id="example1">Example</h2>^M
<div id="gallery">^M
    <ul>^M
        <li>^M
            <a href="/assets/photos/image1.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery').lightBox();">^M
             <%= image_tag("photos/thumb_image1.jpg" ) %>
            </a>^M
        </li>^M
        <li>^M
            <a href="/assets/photos/image2.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
             <%= image_tag("photos/thumb_image2.jpg" ) %>
            </a>
        </li>^M
        <li>^M
            <a href="/assets/photos/image3.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">^M
             <%= image_tag("photos/thumb_image3.jpg" ) %>
            </a>
        </li>^M
        <li>^M
            <a href="photos/image4.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
             <%= image_tag("photos/thumb_image4.jpg" ) %>
            </a>
        </li>^M
        <li>^M
            <a href="photos/image5.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">^M
                  <%= image_tag("photos/thumb_image5.jpg" ) %> ^M
              ^M
            </a>^M
        </li>^M
    </ul>^M
</div>^M
        <h3><a href="#">Другое</a></h3>
        <div>
                <p>
                Cras dictum. Pellentesque habitant morbi tristique senectus et netus
                et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
                faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
                mauris vel est.
                </p>
<div id="gallery">^M
    <ul>^M
        <li>^M
            <a href="/assets/photos/image1.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery').lightBox();">^M
             <%= image_tag("photos/thumb_image1.jpg" ) %>
            </a>^M
        </li>^M
        <li>^M
            <a href="/assets/photos/image2.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
             <%= image_tag("photos/thumb_image2.jpg" ) %>
            </a>
        </li>^M
        <li>^M
            <a href="/assets/photos/image3.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">^M
             <%= image_tag("photos/thumb_image3.jpg" ) %>
            </a>
        </li>^M
        <li>^M
            <a href="photos/image4.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
             <%= image_tag("photos/thumb_image4.jpg" ) %>
            </a>
        </li>^M
        <li>^M
            <a href="photos/image5.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">^M
                  <%= image_tag("photos/thumb_image5.jpg" ) %> ^M
              ^M
            </a>^M
        </li>^M
    </ul>^M
</div> </div>

app/views/pages/_port1.html.erb
<div id="gallery">
    <ul>
        <li>
            <a href="/assets/photos/image1.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery').lightBox();">
	     <%= image_tag("photos/thumb_image1.jpg" ) %>
            </a>
        </li>
        <li>
            <a href="/assets/photos/image2.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
	     <%= image_tag("photos/thumb_image2.jpg" ) %>
            </a>
        </li>
        <li>
            <a href="/assets/photos/image3.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
	     <%= image_tag("photos/thumb_image3.jpg" ) %>
            </a>
        </li>
        <li>
            <a href="photos/image4.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
	     <%= image_tag("photos/thumb_image4.jpg" ) %>
            </a>
        </li>
        <li>
            <a href="photos/image5.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
                  <%= image_tag("photos/thumb_image5.jpg" ) %> 
              
            </a>
        </li>
    </ul>
</div>

app/views/pages/about.html.erb
<h1>Pages#portf</h1>

app/views/pages/clients.html.erb
<h1>Pages#clients</h1>
<p>Find me in app/views/pages/clients.html.erb</p>

app/views/pages/contact.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<h2 id="example1">Example</h2>
<p>Click in the image and see the <strong>jQuery lightBox plugin</strong> in action.</p>
<div id="gallery">
    <ul>
        <li>
            <a href="/assets/photos/image1.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery').lightBox();">
                <img src="/assets/photos/thumb_image1.jpg" width="72" height="72" alt="" />
            </a>
        </li>
        <li>
            <a href="/assets/photos/image2.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
                <img src="/assets/photos/thumb_image2.jpg" width="72" height="72" alt="" />
            </a>
        </li>
        <li>
            <a href="/assets/photos/image3.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
                <img src="/assets/photos/thumb_image3.jpg" width="72" height="72" alt="" />
            </a>
        </li>
        <li>
            <a href="photos/image4.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
                <img src="photos/thumb_image4.jpg" width="72" height="72" alt="" />
            </a>
        </li>
        <li>
            <a href="photos/image5.jpg" title="Utilize a flexibilidade dos seletores da jQuery e crie um grupo de imagens como desejar. $('#gallery a').lightBox();">
                  <%= image_tag("photos/thumb_image5.jpg" ) %> 
              
            </a>
        </li>
    </ul>
</div>


app/views/pages/home.html.erb
<h2>  <%= @title %>  </h2>

<div id="menu_l"> <h3> Пакетное предложение </h3>

	<ul>
	<li> Для сельхозпроизводителей  </li>
	<li> Для сельхозпроизводителей  </li>
	<li> Для сельхозпроизводителей  </li>
	
	</ul>
</div>

app/views/portfolios/.bk_form.html.erb
<%= form_for(@portfolio) do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :title_o %><br />
    <%= f.text_field :title_o %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :image_url_pr %><br />
    <%= f.text_field :image_url_pr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/.index.html.erb
<h1>Listing portfolios</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Title o</th>
    <th>Image url</th>
    <th>Image url pr</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @portfolios.each do |portfolio| %>
  <tr>
    <td><%= portfolio.title %></td>
    <td><%= portfolio.title_o %></td>
    <td><%= portfolio.image_url %></td>
    <td><%= portfolio.image_url_pr %></td>
    <td><%= link_to 'Show', portfolio %></td>
    <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
    <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :title_o %><br />
    <%= f.text_field :title_o %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :image_url_pr %><br />
    <%= f.text_field :image_url_pr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing portfolio</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/new.html.erb
<h1>New portfolio</h1>

<%= render 'form' %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> Название :</b>
  <%= @portfolio.title %>
</p>

<p>
  <b> Описание контента:</b>
  <%= @portfolio.title_o %>
</p>
	<div id="">

<div id="gallery">  <a href="/assets/<%= @portfolio.image_url_pr %>"> 
  <%= image_tag( @portfolio.image_url_pr ,height: "200", widght: "200" ) %> </a>
</div>
</div>

<%= link_to 'Вернуться назад', portfolios_path %>

app/views/upload/save.html.erb
<h1>Upload#save</h1>
<p>Find me in app/views/upload/save.rhtml</p>